# Use container-based infrastructure
sudo: false

language: scala

scala:
   - 2.11.8

branches:
    - master
    - develop

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - vladimir@dokwork.ru


